### ISSUE TITLE
Acción del Botón "enviar" de formularios register/login

### ISSUE THREAD

**Issue by PabloGomezCardozo** [StivenYepesArenas/mercado-liebre#1]
Estiven, muy buena tu página, cumple con todos los requisitos solicitados!.
Una sola sugerencia, los botones "enviar" en los formularios Registro y Login no ejecutan la acción de redirigir al home ("/"). Por lo que veo, si asignaste en el formulario action="/". Quizás no esté funcionando porque a la etiqueta button le falta el tipo type="submit". 
Excelente trabajo!

**Comment by StivenYepesArenas** [comment]
Hola Pablo, ya lo solucione, hice como me sugeriste, no redirigirá al home hasta no tener los campos completados, para que tengas en cuenta. Muchas garcias por la retro.

**Comment by PabloGomezCardozo** [comment]
Quedó perfecto! Cierro el issue
